### ISSUE TITLE
How to simply add a glyph on a Type Safe Builder?

### ISSUE THREAD

**Issue by MindFlare56** [edvin/tornadofx-controlsfx#14]
```
init {
    with(root) {
        label("test")
        FontAwesome.Glyph.ANCHOR //something like that 
    }
}
```

**Comment by edvin** [comment]
Most FontAwesome implementations simply create `Node` instances, so you can assign them to the `graphic` property of your label for example:

```kotlin
override val root = hbox {
    label("test") {
        graphic = FontAwesome.Glyph.ANCHOR
    }
}
```

I also snuck in a best practice for how to create your root node :) No need to instantiate the root node and then use the `with(root)` pattern.

**Comment by MindFlare56** [comment]
Ok thanks, it helped a lot

it was:
```
label("test") {
    val anchor = FontAwesome.Glyph.ANCHOR
    graphic = anchor.toGlyph()
}
```

I really appreciate!

**Comment by edvin** [comment]
No need for the intermediate variable though :)

```kotlin
label("test") {
    graphic = FontAwesome.Glyph.ANCHOR.toGlyph()
}
```

If you use this a lot you could easily create an extension function so you can write:

```kotlin
label("test") {
    icon(FontAwesome.Glyph.ANCHOR)
}
```

.. or something like that :)
