### ISSUE TITLE
Create new release please

### ISSUE THREAD

**Issue by dmoebius** [edvin/tornadofx-controlsfx#7]
Since the latest official release 0.1 (on Sonatype) there are some useful commits which are only available in the snapshots. Please create a new release 0.1.1 or 0.2. Thanks! :)

**Comment by thomasnield** [comment]
@edvin can you pull the trigger?

**Comment by edvin** [comment]
Will do!

**Comment by edvin** [comment]
I'm having issues with the deployment and have to run now, but I'll get to this tomorrow morning. Going to see Deadpool 2, so I'll be home late :)

**Comment by edvin** [comment]
Belay that, seems like I got it working. Forgot about the -Psign parameter :) Release `0.1.1` will be in Maven Central shortly!

**Comment by thomasnield** [comment]
@edvin it's very funny, have fun!

**Comment by edvin** [comment]
Hehe, yeah I enjoyed it :))
